name: Push Folder

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changed file
      uses: crykn/copy_file_to_another_repo_action@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'guides'
        destination_repo: 'SamSaprykin/dest-actions'
        user_email: 'saprykinse@gmail.com'
        user_name: 'SamSaprykin'
        commit_msg: '[GHA] Update the test files.'
        destination_branch: 'main'