name: Push Folder

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Commit latest notebooks to lecture-python.notebooks
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'guides'
          destination-repository-username: 'SamSaprykin'
          destination-repository-name: 'dest-actions'
          commit-message: 'auto publishing updates to blog'
          destination-github-username: 'SamSaprykin'
          user-email: saprykinse@gmail.com